[package]
name = "rust_integration_test"
version = "0.0.1"
edition = "2021"

[dependencies]
rust_a_star = { path = "../rust-a-star" }
rust_bitmap_tools = { path = "../rust-bitmap-tools" }
image = "0.24.2"
arrayvec = "0.7.4"